<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DfE.Core.Libraries.DesignPatterns.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DfE.Core.Libraries.DesignPatterns\DfE.Core.Libraries.DesignPatterns.csproj" />
  </ItemGroup>

</Project>
